version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: INFO
        formatter: simple
        filename: /tmp/info.log  # TODO explain how the filenames are managed
        when: 'midnight'
        interval: 1
        backupCount: 20
        encoding: utf8

    all_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: /tmp/full_log.log  # TODO explain how the filenames are managed
        when: 'midnight'
        interval: 1
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: ERROR
        formatter: simple
        filename: /tmp/errors.log
        interval: 1
        when: 'midnight'
        backupCount: 20
        encoding: utf8

    server_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: /tmp/server.log
        interval: 1
        when: 'midnight'
        backupCount: 20
        encoding: utf8

    manager_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: /tmp/manager.log
        interval: 1
        when: 'midnight'
        backupCount: 20
        encoding: utf8

    sender_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: /tmp/sender.log
        interval: 1
        when: 'midnight'
        backupCount: 20
        encoding: utf8

    ack_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: /tmp/ack.log
        interval: 1
        when: 'midnight'
        backupCount: 20
        encoding: utf8

    difmet_ack_message_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: /tmp/difmet_ack_messages.log
        interval: 1
        when: 'midnight'
        backupCount: 20
        encoding: utf8

    difmet_alarm_message_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: /tmp/difmet_alarm_messages.log
        interval: 1
        when: 'midnight'
        backupCount: 20
        encoding: utf8


    connections_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: INFO
        formatter: simple
        filename: /tmp/connections.log
        interval: 1
        when: 'midnight'
        backupCount: 20
        encoding: utf8

loggers:
    file_manager.manager:
        level: DEBUG
        handlers: [manager_file_handler, info_file_handler, error_file_handler, all_handler]
        propagate: no

    file_sender.sender:
        level: DEBUG
        handlers: [sender_file_handler, info_file_handler, error_file_handler, all_handler]
        propagate: no

    ack_receiver.ack_receiver:
        level: DEBUG
        handlers: [ack_file_handler, info_file_handler, error_file_handler, all_handler]
        propagate: no

    difmet_ack_messages:
        level: DEBUG
        handlers: [difmet_ack_message_handler, all_handler]
        propagate: no

    difmet_alarm_messages:
        level: DEBUG
        handlers: [difmet_alarm_message_handler, all_handler]
        propagate: no

    notification_receiver.receiver:
        level: DEBUG
        handlers: [server_file_handler, info_file_handler, error_file_handler, all_handler]
        propagate: no

    webservice.server.soapInterface:
        level: DEBUG
        handlers: [server_file_handler, info_file_handler, error_file_handler, all_handler]
        propagate: no

    webservice.server.application:
        level: DEBUG
        handlers: [server_file_handler, info_file_handler, error_file_handler, all_handler]
        propagate: no

    utils.database:
        level: DEBUG
        handlers: [server_file_handler, info_file_handler, error_file_handler, all_handler,
                   manager_file_handler, sender_file_handler, ack_file_handler]
        propagate: no

    paramiko.transport:
        level: INFO
        handlers: [manager_file_handler, connections_handler]
        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler, all_handler]